# schema: https://scanner.dev/schema/scanner-detection-rule.v1.json
name: Okta Application Sign-On Policy Modified or Deleted
enabled: true
description: |-
  Detects when an application Sign-on Policy is modified or deleted.

  References:
  * https://developer.okta.com/docs/reference/api/system-log/
  * https://developer.okta.com/docs/reference/api/event-types/

  False Positives:
  * Unknown
severity: Medium
query_text: |-
  %ingest.source_type="okta:system"
  eventType=(
    application.policy.sign_on.update
    application.policy.sign_on.rule.delete
  )
  | stats
    min(timestamp) as firstTime,
    max(timestamp) as lastTime,
    count() as eventCount
    by
    severity,
    eventType,
    actor.id,
    actor.type,
    actor.alternateId,
    actor.displayName,
    outcome.result
time_range_s: 300
run_frequency_s: 60
event_sink_keys:
- medium_severity_alerts

